In [1]:
## Python packages]
from sqlalchemy import create_engine
from sqlalchemy_utils import database_exists, create_database
import psycopg2
import pandas as pd

In [7]:
# Load CSV
import os

csv_path = os.path.join('.','yammer_events.csv')
yammer_events = pd.read_csv(csv_path)

In [9]:
yammer_events.head()

,user_id,occurred_at,event_type,event_name,location,device,user_type
0,10522.0,2014-05-02 11:02:39,engagement,login,Japan,dell inspiron notebook,3.0
1,10522.0,2014-05-02 11:02:53,engagement,home_page,Japan,dell inspiron notebook,3.0
2,10522.0,2014-05-02 11:03:28,engagement,like_message,Japan,dell inspiron notebook,3.0
3,10522.0,2014-05-02 11:04:09,engagement,view_inbox,Japan,dell inspiron notebook,3.0
4,10522.0,2014-05-02 11:03:16,engagement,search_run,Japan,dell inspiron notebook,3.0

In [11]:
import pandasql as ps

In [24]:
# sql_query = """
# SELECT DATE_TRUNC('week', to_timestamp(e.occurred_at,'yyyy/mm/dd HH24:MI:SS')),
#        COUNT(DISTINCT e.user_id) AS weekly_active_users
#   FROM yammer_events e
#  WHERE e.event_type = 'engagement'
#    AND e.event_name = 'login'
#  GROUP BY 1
#  ORDER BY 1
# """


sql_query = """
SELECT * FROM yammer_events WHERE event_type='engagement';
"""

In [26]:
ps.sqldf(sql_query, locals())

,user_id,occurred_at,event_type,event_name,location,device,user_type
0,10522.0,2014-05-02 11:02:39,engagement,login,Japan,dell inspiron notebook,3.0
1,10522.0,2014-05-02 11:02:53,engagement,home_page,Japan,dell inspiron notebook,3.0
2,10522.0,2014-05-02 11:03:28,engagement,like_message,Japan,dell inspiron notebook,3.0
3,10522.0,2014-05-02 11:04:09,engagement,view_inbox,Japan,dell inspiron notebook,3.0
4,10522.0,2014-05-02 11:03:16,engagement,search_run,Japan,dell inspiron notebook,3.0
5,10522.0,2014-05-02 11:03:43,engagement,search_run,Japan,dell inspiron notebook,3.0
6,10612.0,2014-05-01 09:59:46,engagement,login,Netherlands,iphone 5,1.0
7,10612.0,2014-05-01 10:00:18,engagement,like_message,Netherlands,iphone 5,1.0
8,10612.0,2014-05-01 10:00:53,engagement,send_message,Netherlands,iphone 5,1.0
9,10612.0,2014-05-01 10:01:24,engagement,home_page,Netherlands,iphone 5,1.0
10,10612.0,2014-05-01 10:01:52,engagement,like_message,Netherlands,iphone 5,1.0
11,10612.0,2014-05-01 10:02:17,engagement,home_page,Netherlands,iphone 5,1.0
12,10612.0,2014-05-01 10:02:51,engagement,view_inbox,Netherlands,iphone 5,1.0
13,10612.0,2014-05-01 10:03:17,engagement,like_message,Netherlands,iphone 5,1.0
14,10612.0,2014-05-01 10:03:40,engagement,home_page,Netherlands,iphone 5,1.0
15,10612.0,2014-05-01 10:04:06,engagement,send_message,Netherlands,iphone 5,1.0
16,10612.0,2014-05-01 10:04:44,engagement,like_message,Netherlands,iphone 5,1.0
17,10612.0,2014-05-01 10:05:18,engagement,send_message,Netherlands,iphone 5,1.0
18,10736.0,2014-05-09 17:52:45,engagement,login,Austria,iphone 4s,2.0
19,10736.0,2014-05-09 17:53:16,engagement,like_message,Austria,iphone 4s,2.0
20,10736.0,2014-05-09 17:53:51,engagement,send_message,Austria,iphone 4s,2.0
21,10965.0,2014-05-15 13:52:59,engagement,login,Finland,windows surface,3.0
22,10965.0,2014-05-15 13:53:31,engagement,home_page,Finland,windows surface,3.0
23,11020.0,2014-05-08 09:15:35,engagement,login,Japan,macbook air,2.0
24,11020.0,2014-05-08 09:15:58,engagement,home_page,Japan,macbook air,2.0
25,11020.0,2014-05-08 09:16:31,engagement,view_inbox,Japan,macbook air,2.0
26,11020.0,2014-05-08 09:16:58,engagement,home_page,Japan,macbook air,2.0
27,11020.0,2014-05-08 09:17:26,engagement,view_inbox,Japan,macbook air,2.0
28,11020.0,2014-05-08 09:17:56,engagement,send_message,Japan,macbook air,2.0
29,11020.0,2014-05-08 09:18:30,engagement,view_inbox,Japan,macbook air,2.0
...,...,...,...,...,...,...,...
321545,18806.0,2014-08-31 19:42:33,engagement,home_page,Greece,lenovo thinkpad,3.0
321546,18806.0,2014-08-31 19:42:54,engagement,view_inbox,Greece,lenovo thinkpad,3.0
321547,18806.0,2014-08-31 19:43:21,engagement,send_message,Greece,lenovo thinkpad,3.0
321548,18806.0,2014-08-31 19:41:54,engagement,search_autocomplete,Greece,lenovo thinkpad,3.0
321549,18806.0,2014-08-31 19:42:24,engagement,search_autocomplete,Greece,lenovo thinkpad,3.0
321550,18806.0,2014-08-31 19:43:05,engagement,search_autocomplete,Greece,lenovo thinkpad,3.0
321551,18806.0,2014-08-31 19:43:33,engagement,search_autocomplete,Greece,lenovo thinkpad,3.0
321552,18806.0,2014-08-31 19:44:06,engagement,search_autocomplete,Greece,lenovo thinkpad,3.0
321553,18809.0,2014-08-31 23:01:15,engagement,login,Pakistan,dell inspiron notebook,3.0
321554,18809.0,2014-08-31 23:01:46,engagement,like_message,Pakistan,dell inspiron notebook,3.0
321555,18809.0,2014-08-31 23:01:44,engagement,search_autocomplete,Pakistan,dell inspiron notebook,3.0
321556,18809.0,2014-08-31 23:02:05,engagement,search_autocomplete,Pakistan,dell inspiron notebook,3.0
321557,18809.0,2014-08-31 23:02:31,engagement,search_autocomplete,Pakistan,dell inspiron notebook,3.0
321558,18809.0,2014-08-31 23:03:13,engagement,search_autocomplete,Pakistan,dell inspiron notebook,3.0
321559,18809.0,2014-08-31 23:03:39,engagement,search_autocomplete,Pakistan,dell inspiron notebook,3.0
321560,18813.0,2014-08-31 18:44:53,engagement,login,United Kingdom,nexus 10,2.0
321561,18813.0,2014-08-31 18:45:22,engagement,like_message,United Kingdom,nexus 10,2.0
321562,18813.0,2014-08-31 18:45:40,engagement,home_page,United Kingdom,nexus 10,2.0
321563,18813.0,2014-08-31 18:46:20,engagement,view_inbox,United Kingdom,nexus 10,2.0
321564,18813.0,2014-08-31 18:46:57,engagement,home_page,United Kingdom,nexus 10,2.0
321565,18813.0,2014-08-31 18:47:29,engagement,view_inbox,United Kingdom,nexus 10,2.0
321566,18814.0,2014-08-31 12:13:31,engagement,login,Japan,dell inspiron notebook,3.0
321567,18814.0,2014-08-31 12:14:14,engagement,view_inbox,Japan,dell inspiron notebook,3.0
321568,18814.0,2014-08-31 12:14:41,engagement,home_page,Japan,dell inspiron notebook,3.0
321569,18815.0,2014-08-31 13:41:06,engagement,login,Ireland,dell inspiron notebook,2.0
321570,18815.0,2014-08-31 13:41:46,engagement,like_message,Ireland,dell inspiron notebook,2.0
321571,18815.0,2014-08-31 13:42:11,engagement,home_page,Ireland,dell inspiron notebook,2.0
321572,18815.0,2014-08-31 13:42:43,engagement,send_message,Ireland,dell inspiron notebook,2.0
321573,18815.0,2014-08-31 13:43:07,engagement,home_page,Ireland,dell inspiron notebook,2.0
321574,18815.0,2014-08-31 13:43:42,engagement,like_message,Ireland,dell inspiron notebook,2.0